### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by mrbluecoat** [ahsifer/goxdp#5]
Just to verify, to build for ARM, I would do the following, right?

```
git clone https://github.com/ahsifer/goxdp
cd goxdp/server
env GOOS=linux GOARCH=arm64 go build -o goxdp
mv goxdp /usr/local/bin/
```

**Comment by ahsifer** [comment]
Hi @mrbluecoat 
yes, you are correct, but if you want you can also use CGO_ENABLED=0, which makes the output binary not depend on the machine's C libraries.

**Comment by mrbluecoat** [comment]
Thanks. Will that build include the client or do I need to do the same in the `goxdp/client` directory? I ask because this didn't work:

```
# goxdp client --action=load --interfaces=eth0 --mode=skb --dstIP=127.0.0.1 --dstPort=8090
XDP Program loaded successfully
# goxdp client --action=block --src=93.184.215.14/32 --timeout=60 --dstIP=127.0.0.1 --dstPort=8090
src is blocked successfully
# ping -c3 example.com
PING example.com (93.184.215.14) 56(84) bytes of data.
64 bytes from 93.184.215.14 (93.184.215.14): icmp_seq=1 ttl=58 time=8.67 ms
64 bytes from 93.184.215.14 (93.184.215.14): icmp_seq=2 ttl=58 time=8.62 ms
64 bytes from 93.184.215.14 (93.184.215.14): icmp_seq=3 ttl=58 time=8.69 ms
```

P.S. It might be nice to include an ARM variant in your GitHub releases since that architecture is starting to gain in popularity..

**Comment by mrbluecoat** [comment]
Never mind, my mistake - was using the wrong NIC interface.
